# Generated by Django 4.1.7 on 2023-03-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationDetailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_link", models.TextField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                ("drive_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplicationMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "file_field",
                    models.FileField(
                        blank=True, null=True, upload_to="media/examination"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplicationSkillsRequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "experience_in_years",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobExperienceLevelModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobQualificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobTypeTitleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobTypeTitleModel_media",
                        to="jobapplication.jobapplicationmediamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "attchments",
                    models.FileField(
                        blank=True, null=True, upload_to="media/jobApplications/"
                    ),
                ),
                (
                    "job_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONSITE", "ONSITE"),
                            ("REMOTE", "REMOTE"),
                            ("HYBRID", "HYBRID"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notice_period",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "no_of_experience",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_third_party_application",
                    models.BooleanField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobApplicationModel_address",
                        to="company.companyaddressmodel",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="JobApplicationModel_category",
                        to="category.categorymodel",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="JobApplicationModel_company",
                        to="company.companydetailsmodel",
                    ),
                ),
                (
                    "experience_level",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobApplicationModel_experience_level",
                        to="jobapplication.jobexperiencelevelmodel",
                    ),
                ),
                (
                    "job_application_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="JobApplicationModel_job_application_details",
                        to="jobapplication.jobapplicationdetailmodel",
                    ),
                ),
                (
                    "job_type",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobApplicationModel_job_type",
                        to="jobapplication.jobtypetitlemodel",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobApplicationModel_media",
                        to="jobapplication.jobapplicationmediamodel",
                    ),
                ),
                (
                    "qualification",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobApplicationModel_qualification",
                        to="jobapplication.jobqualificationmodel",
                    ),
                ),
                (
                    "skills_required",
                    models.ManyToManyField(
                        blank=True,
                        related_name="JobApplicationModel_skills_required",
                        to="jobapplication.jobapplicationskillsrequired",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="JobApplicationModel_sub_category",
                        to="category.subcategorymodel",
                    ),
                ),
            ],
        ),
    ]
