# Generated by Django 4.1.7 on 2023-03-10 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_usermodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0ea839b0-bf2e-11ed-8e40-46124d953699"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
