# Generated by Django 4.1.7 on 2023-03-10 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "file_field",
                    models.FileField(blank=True, null=True, upload_to="media/courses"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseQuizModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseSectionContentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CourseSectionContentModel_quiz",
                        to="courses.coursequizmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseWhatYouWillLearnModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseWhatYouWillLearnModel_media",
                        to="courses.coursemediamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseVideoMediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "resources",
                    models.FileField(blank=True, null=True, upload_to="media/courses"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseVideoMediaModel_media",
                        to="courses.coursemediamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseUserRequirementsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseUserRequirementsModel_media",
                        to="courses.coursemediamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseThisCourseIncludesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseThisCourseIncludesModel_media",
                        to="courses.coursemediamodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseSectionModel_content",
                        to="courses.coursesectioncontentmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coursesectioncontentmodel",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CourseSectionContentModel_video",
                to="courses.coursevideomediamodel",
            ),
        ),
        migrations.CreateModel(
            name="CourseQuizOptionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseQuizOptionsModel_media",
                        to="courses.coursemediamodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coursequizmodel",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CourseQuizModel_answer",
                to="courses.coursequizoptionsmodel",
            ),
        ),
        migrations.AddField(
            model_name="coursequizmodel",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="CourseQuizModel_media",
                to="courses.coursemediamodel",
            ),
        ),
        migrations.AddField(
            model_name="coursequizmodel",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                related_name="CourseQuizModel_options",
                to="courses.coursequizoptionsmodel",
            ),
        ),
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CourseModel_category",
                        to="category.categorymodel",
                    ),
                ),
                (
                    "course_sections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseModel_course_sections",
                        to="courses.coursesectionmodel",
                    ),
                ),
                (
                    "instructor",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseModel_instructor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseModel_media",
                        to="courses.coursemediamodel",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CourseModel_sub_category",
                        to="category.subcategorymodel",
                    ),
                ),
                (
                    "this_course_include",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseModel_this_course_include",
                        to="courses.coursethiscourseincludesmodel",
                    ),
                ),
                (
                    "user_requirements",
                    models.ManyToManyField(
                        related_name="CourseModel_user_requirements",
                        to="courses.courseuserrequirementsmodel",
                    ),
                ),
                (
                    "what_you_will_learn",
                    models.ManyToManyField(
                        blank=True,
                        related_name="CourseModel_what_you_will_learn",
                        to="courses.coursewhatyouwilllearnmodel",
                    ),
                ),
            ],
        ),
    ]
