# Generated by Django 4.1.7 on 2023-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofilemodel", name="contact_info",),
        migrations.AddField(
            model_name="userprofilemodel",
            name="contact_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_contact_info",
                to="userprofile.usercontactinfomodel",
            ),
        ),
    ]
