# Generated by Django 4.1.7 on 2023-03-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_userprofilemodel_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCertificatesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file_field",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/user_profile/certificate/",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userresumemodel",
            name="file_field",
            field=models.FileField(
                blank=True, null=True, upload_to="media/user_profile/resumes/"
            ),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="certificate",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_certificate",
                to="userprofile.usercertificatesmodel",
            ),
        ),
    ]
