# Generated by Django 4.1.7 on 2023-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_usercertificatesmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofilemodel", name="certificate",),
        migrations.AddField(
            model_name="userprofilemodel",
            name="certificates",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_certificates",
                to="userprofile.usercertificatesmodel",
            ),
        ),
    ]
