# Generated by Django 4.1.7 on 2023-03-13 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0005_remove_userprofilemodel_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpostmodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserPostModel_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
